MODEL:
  META_ARCHITECTURE: "Sigais"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_sigais_backbone"
  RESNETS:
    NORM: "SyncBN"
    # NORM: "BN"
  DECODER:
    NAME: "build_decoder"
    NORM: "SyncBN"
    # NORM: "BN"
  SIGAIS:
    STUFF_AREA: 2048
    CENTER_THRESHOLD: 0.1
    NMS_KERNEL: 7
    TOP_K_INSTANCE: 200
    USE_DEPTHWISE_SEPARABLE_CONV: True
    BENCHMARK_NETWORK_SPEED: False 
  WEIGHTS: ""
  PIXEL_MEAN: [101.676, 99.456, 100.954]
  PIXEL_STD: [49.851, 49.755, 50.721]
DATASETS:
  TRAIN: ("ropeins_train",)
  TEST: ("ropeins_val_homologous","ropeins_val_heterologous")
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 100000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 16
  POLY_LR_POWER: 0.9
  POLY_LR_CONSTANT_ENDING: 0.0
  AMP:
    ENABLED: False
INPUT:
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  FORMAT: "RGB"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (544, 960)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  GAUSSIAN_SIGMA: 10
  IGNORE_STUFF_IN_OFFSET: True
  SMALL_INSTANCE_AREA: 2048
  SMALL_INSTANCE_WEIGHT: 3
  IGNORE_CROWD_IN_SEMANTIC: False
DATALOADER:
  NUM_WORKERS: 16
VERSION: 2
OUTPUT_DIR: ./debug
# SEED: 56523130